const commands = {
    SYNC_ORDERS: "SYNC_ORDERS",
    PUBLISH_ORDER: "PUBLISH_ORDER",
    LOCK_ORDER: "LOCK_ORDER",
    UNLOCK_ORDER: "UNLOCK_ORDER",
    CREATE_ORDER: "CREATE_ORDER",
    UPDATE_ORDER: "UPDATE_ORDER"
};

module.exports = commands;